const express = require("express");
const cheerio = require("cheerio");
const nodemailer = require("nodemailer");
const puppeteer = require("puppeteer-core");
const chromium = require("@sparticuz/chromium");
const path = require("path");
require("dotenv").config();

const app = express();

/* ---------- MIDDLEWARE ---------- */
app.use(express.urlencoded({ extended: true }));
app.use(express.static("public"));

/* ---------- EMAIL ---------- */
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

/* ---------- ROUTES ---------- */
app.get("/", (_, res) => {
  res.sendFile(path.join(__dirname, "public", "index.html"));
});

app.post("/generate-audit", async (req, res) => {
  let browser;

  try {
    const { userName, userEmail, websiteUrl } = req.body;

    /* 1️⃣ Fetch website */
    const response = await fetch(websiteUrl);
    const html = await response.text();
    const $ = cheerio.load(html);

    const title = $("title").text() || "No Title";
    const description =
      $('meta[name="description"]').attr("content") || "No Description";
    const h1 = $("h1").first().text() || "No H1";

    /* 2️⃣ Launch Puppeteer (Railway Safe) */
    browser = await puppeteer.launch({
      args: chromium.args,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
    });

    const page = await browser.newPage();

    /* 3️⃣ PDF DESIGN */
    await page.setContent(`
      <html>
      <body style="font-family:Arial;padding:40px">
        <h1 style="color:#2563eb">SEO Audit Report</h1>
        <p><strong>Name:</strong> ${userName}</p>
        <p><strong>Email:</strong> ${userEmail}</p>
        <p><strong>Website:</strong> ${websiteUrl}</p>
        <hr/>
        <h3>SEO Findings</h3>
        <p><b>Title:</b> ${title}</p>
        <p><b>Description:</b> ${description}</p>
        <p><b>H1:</b> ${h1}</p>
        <p style="margin-top:40px;font-size:12px;color:#666">
          Generated by SEO Audit Tool
        </p>
      </body>
      </html>
    `);

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
    });

    await browser.close();

    /* 4️⃣ SEND EMAIL */
    await transporter.sendMail({
      from: `"SEO Auditor" <${process.env.EMAIL_USER}>`,
      to: userEmail,
      subject: "Your SEO Audit Report",
      text: `Hi ${userName},\n\nYour SEO audit report is attached.`,
      attachments: [
        {
          filename: "SEO_Audit_Report.pdf",
          content: pdfBuffer,
        },
      ],
    });

    /* 5️⃣ RETURN PDF */
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "inline; filename=SEO_Audit_Report.pdf"
    );
    res.send(pdfBuffer);
  } catch (err) {
    if (browser) await browser.close();
    console.error(err);
    res.status(500).send("Audit failed");
  }
});

/* ---------- SERVER ---------- */
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🚀 Server running at http://localhost:${PORT}/`);
});
