const express = require("express");
const cheerio = require("cheerio");
const nodemailer = require("nodemailer");
const puppeteer = require("puppeteer-core");
const chromium = require("@sparticuz/chromium");
const path = require("path");
require("dotenv").config();

const app = express();

/* ---------- MIDDLEWARE ---------- */
app.use(express.json()); // CRITICAL: Allows reading JSON from the frontend fetch
app.use(express.urlencoded({ extended: true }));
app.use(express.static("public"));

/* ---------- EMAIL SETUP ---------- */
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

/* ---------- ROUTES ---------- */
app.get("/", (_, res) => {
  res.sendFile(path.join(__dirname, "public", "index.html"));
});

app.post("/generate-audit", async (req, res) => {
  let browser;

  try {
    const { userName, userEmail, websiteUrl } = req.body;

    if (!websiteUrl) {
      return res.status(400).send("Website URL is required");
    }

    /* 1️⃣ Fetch & Scrape Website */
    const siteRes = await fetch(websiteUrl);
    const html = await siteRes.text();
    const $ = cheerio.load(html);

    const title = $("title").text() || "No Title Found";
    const description = $('meta[name="description"]').attr("content") || "No Meta Description Found";
    const h1 = $("h1").first().text() || "No H1 Tag Found";

    /* 2️⃣ Launch Puppeteer (Railway/Production Config) */
    browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
    });

    const page = await browser.newPage();

    /* 3️⃣ PDF HTML Template */
    await page.setContent(`
      <html>
        <body style="font-family: Arial, sans-serif; padding: 50px; line-height: 1.6;">
          <h1 style="color: #2563eb; border-bottom: 2px solid #2563eb;">SEO Audit Report</h1>
          <div style="margin: 20px 0; padding: 20px; background: #f8fafc; border-radius: 8px;">
            <p><strong>Client Name:</strong> ${userName}</p>
            <p><strong>Website:</strong> <a href="${websiteUrl}">${websiteUrl}</a></p>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
          </div>
          <h2>SEO Highlights</h2>
          <ul>
            <li><strong>Meta Title:</strong> ${title}</li>
            <li><strong>Meta Description:</strong> ${description}</li>
            <li><strong>Main Heading (H1):</strong> ${h1}</li>
          </ul>
          <p style="margin-top: 50px; font-size: 10px; color: #94a3b8; text-align: center;">
            Generated by SEO Auditor Pro
          </p>
        </body>
      </html>
    `);

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
    });

    await browser.close();

    /* 4️⃣ Send Email in Background */
    // We don't "await" this if we want the PDF to show up faster, 
    // but for reliability, we await it here.
    await transporter.sendMail({
      from: `"SEO Auditor" <${process.env.EMAIL_USER}>`,
      to: userEmail,
      subject: `Your SEO Audit for ${websiteUrl}`,
      text: `Hi ${userName},\n\nPlease find your SEO audit report attached.`,
      attachments: [{ filename: "SEO_Audit.pdf", content: pdfBuffer }],
    });

    /* 5️⃣ Send PDF to Browser */
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "inline; filename=Audit.pdf");
    res.send(pdfBuffer);

  } catch (err) {
    if (browser) await browser.close();
    console.error("AUDIT ERROR:", err);
    res.status(500).send("Internal Server Error: " + err.message);
  }
});

/* ---------- START SERVER ---------- */
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🚀 Server running on port ${PORT}`);
});