const express = require('express');
const axios = require('axios');
const cheerio = require('cheerio');
const nodemailer = require('nodemailer');
const path = require('path');

const puppeteer = require('puppeteer'); // LOCAL + PROD SAFE

require('dotenv').config();

const app = express();

/* ---------- MIDDLEWARE ---------- */
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(express.static('public'));

/* ---------- EMAIL ---------- */
const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 465,
  secure: true,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

/* ---------- ROUTES ---------- */
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

app.post('/generate-audit', async (req, res) => {
  const { userName, userEmail, websiteUrl } = req.body;
  let browser;

  try {
    /* 1️⃣ SCRAPE WEBSITE */
    const response = await axios.get(websiteUrl, { timeout: 15000 });
    const $ = cheerio.load(response.data);

    const seoData = {
      title: $('title').text() || 'No Title Found',
      description:
        $('meta[name="description"]').attr('content') ||
        'No Description Found',
      h1: $('h1').first().text() || 'No H1 Found',
      links: $('a').length,
      images: $('img').length,
    };

    /* 2️⃣ LAUNCH PUPPETEER */
    browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });

    const page = await browser.newPage();

    /* 3️⃣ HTML (BEAUTIFUL, LIKE BEFORE) */
    const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8" />
        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 50px;
          }
          h1 {
            color: #2563eb;
          }
          .card {
            margin-top: 20px;
            padding: 20px;
            border-radius: 10px;
            border: 1px solid #ddd;
          }
        </style>
      </head>
      <body>
        <h1>SEO Audit Report</h1>
        <p><strong>Website:</strong> ${websiteUrl}</p>

        <div class="card">
          <p><b>Title:</b> ${seoData.title}</p>
          <p><b>Description:</b> ${seoData.description}</p>
          <p><b>H1:</b> ${seoData.h1}</p>
          <p><b>Links:</b> ${seoData.links}</p>
          <p><b>Images:</b> ${seoData.images}</p>
        </div>

        <p style="margin-top: 40px; font-size: 12px; color: #666;">
          Generated by SEO Audit Tool
        </p>
      </body>
    </html>
    `;

    /* 🔥 THIS IS THE CRITICAL FIX */
    await page.setContent(html, {
      waitUntil: 'networkidle0',
    });

    /* 🔥 WAIT FOR FONTS */
    await page.evaluateHandle('document.fonts.ready');

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
    });

    await browser.close();

    /* 4️⃣ EMAIL */
    await transporter.sendMail({
      from: `"SEO Auditor" <${process.env.EMAIL_USER}>`,
      to: userEmail,
      subject: 'Your SEO Audit Report',
      attachments: [
        {
          filename: 'SEO_Audit_Report.pdf',
          content: pdfBuffer,
        },
      ],
    });

    /* 5️⃣ RETURN PDF */
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      'inline; filename="SEO_Audit_Report.pdf"'
    );
    res.send(pdfBuffer);

  } catch (error) {
    if (browser) await browser.close();
    console.error(error);
    res.status(500).send('Error generating audit');
  }
});

/* ---------- SERVER ---------- */
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🚀 Server running at http://localhost:${PORT}/`);
});
